### ISSUE TITLE
error while searching by area

### ISSUE THREAD

**Issue by nicokant94** [Mte90/WP-OneAndDone#19]
Warning: array_push() expects at least 2 parameters, 1 given in /data/vhosts/mte90.net/wpoad.mte90.net/wp-content/plugins/search-filter-posts-with-ajax/lib/Q_AJAX_Filter_Core.php on line 235

step to reproduce: 
only set Area to Firefox For Android
![screenshot-wpoad mte90 net 2015-06-12 10-45-02](https://cloud.githubusercontent.com/assets/6927678/8126606/4dfe5b66-10f0-11e5-8ed0-84bfee931f8a.png)

**Comment by Mte90** [comment]
Is a bug of the plugin used for the search, mentioned also in https://github.com/Mte90/WP-OneAndDone/issues/17

**Comment by Mte90** [comment]
Fixed in https://wordpress.org/support/topic/warning-after-a-search?replies=1#post-7061236
